[package]
name = "rustcalc"
version = "0.1.0"
authors = ["Raghav Shankar <warpspeedscp@gmail.com>"]

[dependencies]
termion = "*"
scribe = "*"
fst = "*"
fst-regex = "*"
#num = "*"
lazy_static = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
[features]
debug = []